In [1]:
import pandas as pd

In [2]:
import os

In [3]:
os.getcwd()

'C:\\Users\\tarun\\Downloads'

In [4]:
os.chdir("C:/Users/tarun/AI NEXUS/Pandas")

In [6]:
df = pd.read_csv("emp_sal_data.csv")

In [9]:
df[df["city"] == "Jabalpur"]

,empid,empname,city,salary,age,dob,dept
1182,1183,Kabir Mutti,Jabalpur,119002,23,09-07-1971,HR
1194,1195,Zansi Pant,Jabalpur,56924,32,06-07-1989,HR
1316,1317,Netra Chatterjee,Jabalpur,70994,58,11-07-1966,Data Engineering
1393,1394,Timothy Loyal,Jabalpur,37143,28,27-12-1979,Data Engineering
1677,1678,Oscar Saini,Jabalpur,38691,29,06-10-2001,Finance
1702,1703,Balendra Sinha,Jabalpur,84642,57,11-02-2002,Finance

In [14]:
df['sal_rank'] = df['salary'].rank(ascending = False)

In [22]:
df[df['sal_rank'] == 1.0]

     empid     empname         city  salary  age         dob   dept  sal_rank
558    559  Ranbir Das  Mahbubnagar  119756   46  17-09-1987  Sales       1.0

In [24]:
df[df['sal_rank'] == 1.0]

     empid     empname         city  salary  age         dob   dept  sal_rank
558    559  Ranbir Das  Mahbubnagar  119756   46  17-09-1987  Sales       1.0

In [34]:
df['salary'] = df['salary'].astype('int64')

In [35]:
df.dtypes

empid         int64
empname      object
city         object
salary        int64
age           int64
dob          object
dept         object
sal_rank    float64
dtype: object

In [36]:
df['salary'].max()

np.int64(119756)

In [43]:
# find highest salary department wise
df['rank_by_dept'] = df.groupby('dept')['salary'].rank(ascending = False)

In [41]:
df

,empid,empname,city,salary,age,dob,dept,sal_rank,rank_by_dept
0,1,Sai Mallick,Saharanpur,71659,57,18-08-1974,Data Engineering,1110.0,158.0
1,2,Maya Chauhan,Tirupati,82766,26,16-11-1967,IT,850.0,171.0
2,3,Triya Iyengar,Narasaraopet,54495,24,09-10-1968,Data Engineering,1507.0,82.0
3,4,Gaurang Gill,Ahmedabad,67736,52,04-05-1998,Marketing,1222.0,114.0
4,5,Kai Garde,Gurgaon,31898,26,16-06-1988,HR,1959.0,10.0
...,...,...,...,...,...,...,...,...,...
1995,1996,Varenya Karnik,Udupi,84663,46,20-05-1987,IT,810.0,178.0
1996,1997,Varenya Talwar,Erode,83597,49,08-02-2004,Data Engineering,834.0,211.0
1997,1998,Chaitanya Chaudhuri,Ujjain,118020,52,08-07-1984,Data Engineering,47.0,332.0
1998,1999,Kavya Bobal,Amroha,114250,53,15-11-2002,IT,142.0,305.0
1999,2000,Fitan Comar,Warangal,71818,43,11-01-2002,HR,1108.0,169.0

In [44]:
df[df['rank_by_dept'] == 1.0]

,empid,empname,city,salary,age,dob,dept,sal_rank,rank_by_dept
199,200,Tara Tailor,Gorakhpur,119330,56,26-09-1965,HR,8.0,1.0
558,559,Ranbir Das,Mahbubnagar,119756,46,17-09-1987,Sales,1.0,1.0
1044,1045,Siya Roy,Bhagalpur,119256,25,07-10-1971,Finance,10.0,1.0
1282,1283,Daksh Thaman,Raurkela Industrial Township,119178,59,01-03-1966,IT,13.0,1.0
1565,1566,Utkarsh Walla,Chittoor,119739,52,27-04-1979,Data Engineering,2.0,1.0
1855,1856,Raksha Kaul,Jaipur,119564,42,01-11-1992,Marketing,4.0,1.0

In [46]:
df['rank'] = df['salary'].rank(method = 'max')

In [47]:
df

,empid,empname,city,salary,age,dob,dept,sal_rank,rank_by_dept,rank
0,1,Sai Mallick,Saharanpur,71659,57,18-08-1974,Data Engineering,1110.0,179.0,891.0
1,2,Maya Chauhan,Tirupati,82766,26,16-11-1967,IT,850.0,167.0,1151.0
2,3,Triya Iyengar,Narasaraopet,54495,24,09-10-1968,Data Engineering,1507.0,255.0,494.0
3,4,Gaurang Gill,Ahmedabad,67736,52,04-05-1998,Marketing,1222.0,189.0,779.0
4,5,Kai Garde,Gurgaon,31898,26,16-06-1988,HR,1959.0,345.0,42.0
...,...,...,...,...,...,...,...,...,...,...
1995,1996,Varenya Karnik,Udupi,84663,46,20-05-1987,IT,810.0,160.0,1191.0
1996,1997,Varenya Talwar,Erode,83597,49,08-02-2004,Data Engineering,834.0,126.0,1167.0
1997,1998,Chaitanya Chaudhuri,Ujjain,118020,52,08-07-1984,Data Engineering,47.0,5.0,1954.0
1998,1999,Kavya Bobal,Amroha,114250,53,15-11-2002,IT,142.0,33.0,1859.0
1999,2000,Fitan Comar,Warangal,71818,43,11-01-2002,HR,1108.0,186.0,893.0

In [48]:
df['dense'] = df['salary'].rank(method='dense')

In [63]:
df['rn'] = df.groupby('dept').cumcount()+1

In [64]:
df.head(10)

,empid,empname,city,salary,age,dob,dept,sal_rank,rank_by_dept,rank,dense,lag,lead,rn
0,1,Sai Mallick,Saharanpur,71659,57,18-08-1974,Data Engineering,1110.0,179.0,891.0,880.0,NaN,53996.0,1
1,2,Maya Chauhan,Tirupati,82766,26,16-11-1967,IT,850.0,167.0,1151.0,1136.0,NaN,40667.0,1
2,3,Triya Iyengar,Narasaraopet,54495,24,09-10-1968,Data Engineering,1507.0,255.0,494.0,489.0,NaN,30605.0,2
3,4,Gaurang Gill,Ahmedabad,67736,52,04-05-1998,Marketing,1222.0,189.0,779.0,772.0,NaN,49519.0,1
4,5,Kai Garde,Gurgaon,31898,26,16-06-1988,HR,1959.0,345.0,42.0,41.0,NaN,88277.0,1
5,6,Janya Divan,Ajmer,53996,41,26-04-1971,Finance,1513.0,245.0,488.0,483.0,71659.0,61913.0,1
6,7,Ryan Thaker,Gudivada,40667,36,24-07-1991,Sales,1778.0,314.0,223.0,221.0,82766.0,109620.0,1
7,8,Vasatika Shankar,Raebareli,30605,50,29-06-1973,Marketing,1988.0,299.0,13.0,13.0,54495.0,104285.0,2
8,9,Unni Zachariah,Machilipatnam,49519,57,25-03-2003,IT,1606.0,272.0,395.0,391.0,67736.0,101046.0,2
9,10,Orinder Bath,Sangli-Miraj & Kupwad,88277,49,11-12-1986,Marketing,734.0,114.0,1267.0,1251.0,31898.0,94271.0,3

In [54]:
df['lag'] = df['salary'].shift(5)

In [56]:
df['lead'] = df['salary'].shift(-5)

In [66]:
temp = df[['empid','empname','salary','dept','rn']]

In [67]:
temp

      empid              empname  salary              dept   rn
0         1          Sai Mallick   71659  Data Engineering    1
1         2         Maya Chauhan   82766                IT    1
2         3        Triya Iyengar   54495  Data Engineering    2
3         4         Gaurang Gill   67736         Marketing    1
4         5            Kai Garde   31898                HR    1
...     ...                  ...     ...               ...  ...
1995   1996       Varenya Karnik   84663                IT  336
1996   1997       Varenya Talwar   83597  Data Engineering  335
1997   1998  Chaitanya Chaudhuri  118020  Data Engineering  336
1998   1999          Kavya Bobal  114250                IT  337
1999   2000          Fitan Comar   71818                HR  354

[2000 rows x 5 columns]

In [71]:
temp["last_2_days"] = temp['salary'].rolling(window = 2).sum()

C:\Users\tarun\AppData\Local\Temp\ipykernel_9220\2100986048.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp["last_2_days"] = temp['salary'].rolling(window = 2).sum()

In [72]:
temp

      empid              empname  salary              dept   rn  last_2_days
0         1          Sai Mallick   71659  Data Engineering    1          NaN
1         2         Maya Chauhan   82766                IT    1     154425.0
2         3        Triya Iyengar   54495  Data Engineering    2     137261.0
3         4         Gaurang Gill   67736         Marketing    1     122231.0
4         5            Kai Garde   31898                HR    1      99634.0
...     ...                  ...     ...               ...  ...          ...
1995   1996       Varenya Karnik   84663                IT  336     160132.0
1996   1997       Varenya Talwar   83597  Data Engineering  335     168260.0
1997   1998  Chaitanya Chaudhuri  118020  Data Engineering  336     201617.0
1998   1999          Kavya Bobal  114250                IT  337     232270.0
1999   2000          Fitan Comar   71818                HR  354     186068.0

[2000 rows x 6 columns]

In [74]:
temp["last_3_days_avg"] = temp['salary'].rolling(window = 3).mean()
temp

C:\Users\tarun\AppData\Local\Temp\ipykernel_9220\3676444566.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp["last_3_days_avg"] = temp['salary'].rolling(window = 3).mean()

,empid,empname,salary,dept,rn,last_2_days,last_3_days_avg
0,1,Sai Mallick,71659,Data Engineering,1,NaN,NaN
1,2,Maya Chauhan,82766,IT,1,154425.0,NaN
2,3,Triya Iyengar,54495,Data Engineering,2,137261.0,69640.000000
3,4,Gaurang Gill,67736,Marketing,1,122231.0,68332.333333
4,5,Kai Garde,31898,HR,1,99634.0,51376.333333
...,...,...,...,...,...,...,...
1995,1996,Varenya Karnik,84663,IT,336,160132.0,83688.000000
1996,1997,Varenya Talwar,83597,Data Engineering,335,168260.0,81243.000000
1997,1998,Chaitanya Chaudhuri,118020,Data Engineering,336,201617.0,95426.666667
1998,1999,Kavya Bobal,114250,IT,337,232270.0,105289.000000
1999,2000,Fitan Comar,71818,HR,354,186068.0,101362.666667

In [75]:
temp["max_in_last_3days"] = temp['salary'].rolling(window = 3).max()
temp

C:\Users\tarun\AppData\Local\Temp\ipykernel_9220\2889825867.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp["max_in_last_3days"] = temp['salary'].rolling(window = 3).max()

,empid,empname,salary,dept,rn,last_2_days,last_3_days_avg,max_in_last_3days
0,1,Sai Mallick,71659,Data Engineering,1,NaN,NaN,NaN
1,2,Maya Chauhan,82766,IT,1,154425.0,NaN,NaN
2,3,Triya Iyengar,54495,Data Engineering,2,137261.0,69640.000000,82766.0
3,4,Gaurang Gill,67736,Marketing,1,122231.0,68332.333333,82766.0
4,5,Kai Garde,31898,HR,1,99634.0,51376.333333,67736.0
...,...,...,...,...,...,...,...,...
1995,1996,Varenya Karnik,84663,IT,336,160132.0,83688.000000,90932.0
1996,1997,Varenya Talwar,83597,Data Engineering,335,168260.0,81243.000000,84663.0
1997,1998,Chaitanya Chaudhuri,118020,Data Engineering,336,201617.0,95426.666667,118020.0
1998,1999,Kavya Bobal,114250,IT,337,232270.0,105289.000000,118020.0
1999,2000,Fitan Comar,71818,HR,354,186068.0,101362.666667,118020.0

In [76]:
temp["min_in_last_3days"] = temp['salary'].rolling(window = 3).min()
temp

C:\Users\tarun\AppData\Local\Temp\ipykernel_9220\1970696741.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp["min_in_last_3days"] = temp['salary'].rolling(window = 3).min()

,empid,empname,salary,dept,rn,last_2_days,last_3_days_avg,max_in_last_3days,min_in_last_3days
0,1,Sai Mallick,71659,Data Engineering,1,NaN,NaN,NaN,NaN
1,2,Maya Chauhan,82766,IT,1,154425.0,NaN,NaN,NaN
2,3,Triya Iyengar,54495,Data Engineering,2,137261.0,69640.000000,82766.0,54495.0
3,4,Gaurang Gill,67736,Marketing,1,122231.0,68332.333333,82766.0,54495.0
4,5,Kai Garde,31898,HR,1,99634.0,51376.333333,67736.0,31898.0
...,...,...,...,...,...,...,...,...,...
1995,1996,Varenya Karnik,84663,IT,336,160132.0,83688.000000,90932.0,75469.0
1996,1997,Varenya Talwar,83597,Data Engineering,335,168260.0,81243.000000,84663.0,75469.0
1997,1998,Chaitanya Chaudhuri,118020,Data Engineering,336,201617.0,95426.666667,118020.0,83597.0
1998,1999,Kavya Bobal,114250,IT,337,232270.0,105289.000000,118020.0,83597.0
1999,2000,Fitan Comar,71818,HR,354,186068.0,101362.666667,118020.0,71818.0

In [82]:
temp = pd.read_csv("commodity_pivot.csv")

In [83]:
temp

   product  month  sales
0   copper  April     76
1     gold  April     76
2   silver  April     87
3   copper    Feb     65
4     gold    Feb     87
5   silver    Feb     98
6   copper    Jan     56
7     gold    Jan     45
8   silver    Jan     67
9   copper  March    324
10    gold  March     45
11  silver  March    345

In [84]:
tempp = temp.pivot(index='product', columns='month', values='sales')

In [89]:
tempp.loc[['copper','silver']]

month    April  Feb  Jan  March
product
copper      76   65   56    324
silver      87   98   67    345

In [98]:
tempp.loc['Jan']

KeyError: 'Jan'